# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Releaseguard < Formula
  desc "Artifact policy engine — scan, harden, sign, and verify release artifacts before they ship."
  homepage "https://github.com/Helixar-AI/ReleaseGuard"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Helixar-AI/ReleaseGuard/releases/download/v0.1.0/releaseguard-0.1.0-darwin-amd64.tar.gz"
      sha256 "4fcb3019d71462057a89f02337030f27df256b1a4656f2e711556b8c3fe9bdb3"

      define_method(:install) do
        bin.install "releaseguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Helixar-AI/ReleaseGuard/releases/download/v0.1.0/releaseguard-0.1.0-darwin-arm64.tar.gz"
      sha256 "2ecbc64bb7ad0d93e7ba64c39370b4fbb9750ec67c2b711869cb29ccab81984f"

      define_method(:install) do
        bin.install "releaseguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Helixar-AI/ReleaseGuard/releases/download/v0.1.0/releaseguard-0.1.0-linux-amd64.tar.gz"
      sha256 "242286b3300817c68558aab153035a7f6797665ddfe41641d4efece85a240eaf"
      define_method(:install) do
        bin.install "releaseguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Helixar-AI/ReleaseGuard/releases/download/v0.1.0/releaseguard-0.1.0-linux-arm64.tar.gz"
      sha256 "76c9389c4e73a5fc0d41107e30cd0539bfb484c3806acc9bd206f0a7cd9e2e70"
      define_method(:install) do
        bin.install "releaseguard"
      end
    end
  end

  test do
    system "#{bin}/releaseguard", "--version"
  end
end
